# Triggered when automate and coverage-report 
# finish the respective workflow run
# This is run to push the changes commited 
# in those previous workflow and update git.

name: generate-update

on:
  workflow_run:
    workflows: ["automate", "coverage-report"]
    types:
      - completed

jobs:
  push-changes:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ssh-key:
            ${{secrets.DEPLOY_ACTION_SECRET}}
      #----------------------------------------------
      #       set up python
      #----------------------------------------------
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      #----------------------------------------------
      #       push changes to repo
      #----------------------------------------------
      - name: Update git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push -f




